// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnycK89JHTM0aiKMIv_1rS2RkuBkeGwkc',
    appId: '1:317770655267:web:2d191aaccb12d4a5bbf396',
    messagingSenderId: '317770655267',
    projectId: 'the-brew-crew-e2714',
    authDomain: 'the-brew-crew-e2714.firebaseapp.com',
    storageBucket: 'the-brew-crew-e2714.appspot.com',
    measurementId: 'G-EEK7CY2Y84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyO4P7J8Go0EUjKc0drtbWhXxOxN62ubI',
    appId: '1:317770655267:android:0743a728912d5c89bbf396',
    messagingSenderId: '317770655267',
    projectId: 'the-brew-crew-e2714',
    storageBucket: 'the-brew-crew-e2714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthj8mkcanVFKW_t7VoRwGifhWKcW_HTA',
    appId: '1:317770655267:ios:1d80259b4eb9a976bbf396',
    messagingSenderId: '317770655267',
    projectId: 'the-brew-crew-e2714',
    storageBucket: 'the-brew-crew-e2714.appspot.com',
    iosClientId: '317770655267-jcfdgiact52l5483le9aae3t5ddjhbvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBrewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCthj8mkcanVFKW_t7VoRwGifhWKcW_HTA',
    appId: '1:317770655267:ios:1d80259b4eb9a976bbf396',
    messagingSenderId: '317770655267',
    projectId: 'the-brew-crew-e2714',
    storageBucket: 'the-brew-crew-e2714.appspot.com',
    iosClientId: '317770655267-jcfdgiact52l5483le9aae3t5ddjhbvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBrewCrew',
  );
}
